apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: allegro-service-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: allegro-service-secret
    creationPolicy: Owner
  data:
    - secretKey: ALLEGRO_CLIENT_SECRET
      remoteRef:
        key: secret/prod/allegro-service
        property: ALLEGRO_CLIENT_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/prod/allegro-service
        property: DATABASE_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/allegro-service
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/allegro-service
        property: JWT_SECRET
    - secretKey: PAYMENT_API_KEY
      remoteRef:
        key: secret/prod/allegro-service
        property: PAYMENT_API_KEY
    - secretKey: PAYMENT_APPLICATION_ID
      remoteRef:
        key: secret/prod/allegro-service
        property: PAYMENT_APPLICATION_ID
    - secretKey: PAYMENT_WEBHOOK_API_KEY
      remoteRef:
        key: secret/prod/allegro-service
        property: PAYMENT_WEBHOOK_API_KEY
